{
 "title": "Appointment Backend Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(nodejs_version_info, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Reqs Per Route",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method, path)(increase(http_requests_total[$__rate_interval]))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "P50 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le, path, method) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "P95 ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path, method) (rate(http_request_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  { "title": "Infra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(nodejs_version_info) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}} - {{space}}"
    }
   ]
  }
 ]
}