@baseUrl = http://localhost:3000
@json = application/json
@storeId = 11111111-1111-4111-8111-111111111111
@accountId = 22222222-2222-4222-8222-222222222222

### List accounts
GET {{baseUrl}}/accounts?storeId={{storeId}}&page=1&limit=10

### Get account by id
GET {{baseUrl}}/accounts/{{accountId}}

### Create account
POST {{baseUrl}}/accounts
Content-Type: {{json}}

{
  "name": "Administrador",
  "taxId": "12345678901",
  "cellphone": "11988887777",
  "password": "12345678",
  "storeId": "{{storeId}}"
}

### Update account
PATCH {{baseUrl}}/accounts/{{accountId}}
Content-Type: {{json}}

{
  "name": "Administrador Atualizado",
  "cellphone": "11977776666"
}

### Delete account
DELETE {{baseUrl}}/accounts/{{accountId}}
