@baseUrl = http://localhost:3000
@json = application/json
@storeId = 11111111-1111-4111-8111-111111111111
@accountId = 22222222-2222-4222-8222-222222222222
@professionalId = 44444444-4444-4444-8444-444444444444

### List professionals
GET {{baseUrl}}/professionals?storeId={{storeId}}&page=1&limit=10

### Get professional by id
GET {{baseUrl}}/professionals/{{professionalId}}

### Create professional
POST {{baseUrl}}/professionals
Content-Type: {{json}}

{
  "accountId": "{{accountId}}"
}

### Update professional
PATCH {{baseUrl}}/professionals/{{professionalId}}
Content-Type: {{json}}

{
  "accountId": "{{accountId}}"
}

### Delete professional
DELETE {{baseUrl}}/professionals/{{professionalId}}
